name: Test, Build and Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set Node.js 12.x
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Install dependencies
        run: |
          npm install

      - name: Unit test
        run: |
          npm test

      - name: Build
        run: |
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy build to S3
        run: |
          aws s3 sync build s3://junior-reaktor.ykitest.fi --delete
          aws s3 cp build/index.html s3://junior-reaktor.ykitest.fi --cache-control no-store
          aws s3 cp build/service-worker.js s3://junior-reaktor.ykitest.fi --cache-control no-store
          aws s3 cp build/service-worker.js.map s3://junior-reaktor.ykitest.fi --cache-control no-store